language: php

php : '5.6'

before_script:
    - rm composer.json
    - mv composer_travis.json composer.json
    - composer install
    - php -d always_populate_raw_post_data=-1 -S 127.0.0.1:8000 -t demo > httpd.log 2>&1 &
    - phantomjs --webdriver=8001 > phantomjs.log 2>&1 &
    - sleep 3
    
script: 
    - phpunit -c build/phpunit.xml tests/
    - ./bin/behat -p phantomjs

after_success:
    - bash <(curl -s https://codecov.io/bash)
